### ISSUE TITLE
Integration tests take a long time

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/integration-tests#3]
Currently, integration tests take over an hour to complete. @bartek mentioned that the speed is limited by ngrok tunnels. We can use max 2 tunnels at the same time so we can only have 2 simultaneous jobs.

Is the limitation tunnels or processes?

If we wanted to speed this up, we could

1) upgrade our ngrok service. It looks like for a [few dollars a month](https://ngrok.com/pricing) we could get 8 or 12 tunnels, and 1 or 2 simultaneous ngrok processes.

2) try [Serveo](https://serveo.net/). It's an ngrok replacement which allows 3 simultaneous tunnels for free. The site also says

> 
> Host it yourself
> 
> This free version is intended for evaluative and personal use and allows no more than 3 total simultaneous tunnels per instance.
> 
> Email me at trevor@serveo.net if you're interested in licensing Serveo for business use or otherwise need more than 3 tunnels at a time.

**Comment by bartekn** [comment]
> upgrade our ngrok service. It looks like for a few dollars a month we could get 8 or 12 tunnels, and 1 or 2 simultaneous ngrok processes.

I think we are limited to "online ngrok process" not "tunnels/ngrok process". You can't get more than 2 using ngrok.io.

**Comment by leighmcculloch** [comment]
Something must have changed since this issue was opened. The builds currently take ~3-4 minutes. We're running three different configurations in serial as part of the build, so in total it's taking ~10 minutes, which I don't think is too bad.

**Comment by ire-and-curses** [comment]
Doing some digging we remembered that in [e130fd09](https://github.com/stellar/integration-tests/commit/dc996e7c0fcfa19c14e12a6caf9847b6e130fd09) many tests of older versions were removed, because of a restart bug in streaming payments that caused intermittent failures in the tests. Closing this.
